name: MoreEnchantments-GeyserSupport
version: '${project.version}'
main: org.MEGeyserSupport.MEGeyserSupport
api-version: '1.20'
depend: ["MoreEnchantments"]
softdepend: ["Geyser-Spigot", "Floodgate"]